### ISSUE TITLE
Add a gentle reminder to share

### ISSUE THREAD

**Issue by AndrewMagliozzi** [FinalsClub/karmaworld#140]
On notes pages, remind users about the virtues of sharing.  Perhaps an upload button or some other prompt.

**Comment by btbonval** [comment]
The course page has a pretty large Add Note button, the notes page has a small popup that encourages users to get involved with definitions, and the karma points system seems like a strong encouragement to share.

I think this ticket has been resolved, but perhaps there was a more specific goal for this ticket that isn't answered by the aforementioned features?

**Comment by AndrewMagliozzi** [comment]
close it
