### ISSUE TITLE
Edit Notes

### ISSUE THREAD

**Issue by AndrewMagliozzi** [FinalsClub/karmaworld#272]
Allow users to collaboratively edit each others' notes and study guides.  

We must find an open source option for doing this easily.  It should ideally use markdown.  Questions:

 - Can we convert our HTML to markdown (and back) easily?
 - How will we deal with edit history and diff-ing?
 - What existing open source tools can help with this?

Some potential open source options for us to consider:

 - [Etherpad](https://github.com/ether/etherpad-lite/wiki) and its [many plugins](https://github.com/ether/etherpad-lite/wiki/Available-Plugins)
 - [EpicEditor](http://epiceditor.com/#why)
 - [Hallo](http://hallojs.org/) and the [code here](https://github.com/bergie/hallo)
 - [StackEdit](https://stackedit.io/) and the [code here](https://github.com/benweet/stackedit/)
 - [Laverna](https://github.com/Laverna/laverna)
 - Others?

One closed source option might also be:

 - [The Draft API](https://draftin.com/) for diffs, forks, and edit history

**Comment by btbonval** [comment]
Public Lab recently had a discussion about Markdown being unfriendly to new users, so there's a discussion of alternative software which is inherently markdown but has nice editors.
https://github.com/publiclab/plots2/issues/151

**Comment by btbonval** [comment]
From that thread, I found VueJS which looked like a good FOSS solution.
http://vuejs.org/examples/

**Comment by btbonval** [comment]
Not that typing markdown in a browser would ever be easy on a phone, but I just looked at the VueJS example site on my mobile phone. Looks alright.

**Comment by AndrewMagliozzi** [comment]
If we go with Etherpad (as I think I'm inclined), here is a repo that adds Markdown support:

https://github.com/JohnMcLear/ep_markdown

**Comment by btbonval** [comment]
That looks handy. I'll cross post to other list as Public Lab already uses etherpad.

The only problem I see with that is we'd have to run etherpad on a node.js stack with access to the same database as the python stack.

That shouldn't be a huge issue. I think we can run a node Heroku app which points at the same internet-accessible database with no additional cost.

**Comment by btbonval** [comment]
Oh, that project is basically dead and there is no clear licensing :(

**Comment by AndrewMagliozzi** [comment]
Which project is dead?

**Comment by AndrewMagliozzi** [comment]
here's a list of all existing etherpad plugins:

https://github.com/ether/etherpad-lite/wiki/Plugin,-a-list

**Comment by btbonval** [comment]
ep_markdown specifically hasn't been touched in over a year and has no license in the source code or the package.json file. It is not MIT license, GPL, or anything. We'd need to contact the author and request a license be included or special permission to use.

If there are other, better maintained, more clearly licensed markdown plugins for etherpad, that would be handy.

**Comment by btbonval** [comment]
I can't find source code or licensing for the only other markdown plugin, which is called `ep_markdownify`.

From the package description, it disables the GUI buttons in favor of supporting markdown formatting. If we could get license information and it allows us to fork development of `ep_markdown`, I suspect that would be the better choice to `ep_markdownify`.

**Comment by btbonval** [comment]
Posted an issue to `ep_markdown` requesting license information be included.

**Comment by btbonval** [comment]
Author asked me to add Apache 2 license, I'm guessing as a pull request. `ep_markdown` looks much better with an Apache 2 license.

**Comment by btbonval** [comment]
PR created and accepted. `ep_markdown` is now forkable with an Apache 2 license. Sweet. We can go this route now if desired.

**Comment by btbonval** [comment]
@yourcelf suggests we move to HTML as our primary storage format instead of markdown.

We could add a markdown-HTML conversion step to sanitize/cleanup the HTML with a markdown engine, but store that HTML output as the primary note content for editing.

The suggestion is because there are more rich text editors that operate on HTML.

**Comment by btbonval** [comment]
@yourcelf made a good argument against Etherpad because

1. its storage system is separate and would not integrate into our existing database, so we'd either have to import/export or store all notes directly in Etherpad
1. there's a strong latency and Etherpad does not scale well to large numbers

**Comment by btbonval** [comment]
Possible workflow for migration to HTML:

1. add a field to store HTML
2. migrate existing markdown into the HTML field
3. update rendering to drop notes into the HTML field and not markdown
4. remove markdown field
5. rename all markdown references in the code (e.g. `NoteMarkdown` class) to be more generalized concepts of Note editing.

**Comment by btbonval** [comment]
@AndrewMagliozzi I think we have successfully implemented this ticket for Edit Notes, as we can edit certain notes in production. Good to close?

**Comment by AndrewMagliozzi** [comment]
yes, good to close.  It may need some tweaking for the permissions on who
gets to edit, but it's definitely good for now.
