### ISSUE TITLE
selenium firefox tests fail on headless systems

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#277]
The dev VM has no GUI, so Firefox will have to run headless (if that is even a thing).

Otherwise, this error occurs:

```
WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: no display specified\n'
```

possible fix from 2008 to run a virtual X frame buffer:
http://www.alittlemadness.com/2008/03/05/running-selenium-headless/

Here is a post about using Selenium WebDriver for headless testing with Firefox and Ubuntu (our use case):
http://www.installationpage.com/selenium/how-to-run-selenium-headless-firefox-in-ubuntu/

WebDriver info (appears to be part of Selenium 2.0):
http://docs.seleniumhq.org/projects/webdriver/

Python's selenium bindings are already for WebDriver?
https://pypi.python.org/pypi/selenium

**Comment by bravenewprince** [comment]
This was super helpful. Thank you.
