### ISSUE TITLE
Fix Add Course button to use Department and Professor models

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#294]
School is a nullable foreign key transitioning out of the Course model.

Unfortunately we haven't updated the Add Course button to make use of the Department model in Course which is replacing School's functionality. Javascript should prevent any problems, but it looks like a possible spammer added a course without a school (likely bypassing the javascript).

Course's "get_absolute_url" relies on `self.school.slug`, so if there is no school, that line crashes. I installed a hotfix on production which tries that, and upon error, makes the absolute url `/course/<course-slug>` since the school slug in `/<school-slug>/<course-slug>/` is not meaningful (we ignore it).

The correct "fix" is to support adding the school by way of department. If no department is specified, each school may have an empty department for the time being, but the empty department will still tie together a course to a school.

There is also a professor model which exists but is not used by Add Course. This shouldn't break things, but we are transitioning away from professor_email and professor_name inside Course.

**Comment by blag** [comment]
Hi all, sorry to dredge up the past here...

I became a/the maintainer for django-smart-selects a few weeks ago, and I was wondering if there was anything I needed to look into for getting django-smart-selects and django-ajax-selects playing nice together.

Specifically, I'd like to figure out if I can close [django-smart-selects issue #32](https://github.com/digi604/django-smart-selects/issues/32), so if you have an easy way to test it and get me troubleshooting information (_cough_ or a PR _cough_) I'd appreciate it.

Also, it looks like django-ajax-selects _might_ have fixed this with [their PR #59](https://github.com/crucialfelix/django-ajax-selects/pull/59), so if you haven't updated to that yet, you might want to try that.

And finally, if you have any questions or suggestions for additional documentation I can write for django-smart-selects let me know and I'll work on it.

Thanks!

**Comment by btbonval** [comment]
I don't think anyone has looked at this code base in a few years. Reviewing the notes, the two comments that seem most relevant would be:
* https://github.com/FinalsClub/karmaworld/issues/294#issuecomment-34538227
* https://github.com/FinalsClub/karmaworld/issues/294#issuecomment-34539308

It looks like the problem had to do with `ChainedModelChoiceField`, but I'm not sure what I meant 2 years ago with "it lacks control over newly created fields." It probably made a lot of sense in some context though.

**Comment by btbonval** [comment]
@blag 

I don't think anyone has looked at this code base in a few years. Reviewing the notes, the two comments that seem most relevant would be:
- https://github.com/FinalsClub/karmaworld/issues/294#issuecomment-34538227
- https://github.com/FinalsClub/karmaworld/issues/294#issuecomment-34539308

It looks like the problem had to do with `ChainedModelChoiceField`, but I'm not sure what I meant 2 years ago with "it lacks control over newly created fields." It probably made a lot of sense in some context though.

**Comment by blag** [comment]
@btbonval Thanks for the quick response.

I do know that django-smart-selects cannot (yet) query over multiple model relations - only one for now. It looked like that was a pretty solid requirement for you back then, so D-S-S wouldn't have been a great fit for you anyway. Still wouldn't be until [PR #94](https://github.com/digi604/django-smart-selects/pull/94) gets updated and merged.

But either way, now that I'm a contributor, django-smart-selects is back to "maintained" status, so if this code ever gets resurrected or if you have a similar use case in the future, definitely take another look at django-smart-selects and ping me if you need any help/guidance/better documentation/new features/whatever. Cheers!

**Comment by blag** [comment]
As I explained in [#94](https://github.com/digi604/django-smart-selects/pull/94), allowing arbitrary queries on related model a security incident waiting to happen, so I won't be accepting any PRs implementing this unless somebody can come up with a secure by default access control. Sorry!

Edit: Fixed link to point to django-smart-selects pull request.
