### ISSUE TITLE
html2text creates ill formatted markdown when user has space delimited formatting

### ISSUE THREAD

**Issue by JHilker** [FinalsClub/karmaworld#356]
Related to https://github.com/FinalsClub/karmaworld/issues/332

Hack was introduced into global.css to make code blocks generated by marked.js look like normal text. https://github.com/FinalsClub/karmaworld/pull/355

Our branch of html2text currently creates a full line break for every p tag in the google doc instead of ever using soft line breaks.  This decision was made to increase the likelihood of good formatting for users who never use newlines in between sections in their notes.

However, in cases where whitespace is used to format these lines, markdown interprets this as a code block due to the new line above it. In these cases we should not have a newline above the space formatted line, and should instead use a soft line break (two spaces.)

This would require either checking the nested contents of everything included in the tag we are parsing, or possibly doing a regex search at the end.  Neither of these scenarios are ideal.

I think this is for the most part a corner case we shouldn't stress over unless it becomes clear that it is a common issue amongst our users.

**Comment by btbonval** [comment]
This issue seems related to #227 , which was closed.

With the move to HTML as a primary source in #272 , the markdown engine might end up resolving or at least changing some of the problems noted in this issue.

I think we can close this and raise a new issue if a related problem arises with the changes being made.

**Comment by btbonval** [comment]
Markdown is no longer primary, but vestigial. There might be html2text issues that remain, but they will no longer be related to markdown. HTML is the primary note storage format now.
