### ISSUE TITLE
Download documents adds points to DL own note

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#383]
Downloading a document claims that it will cost -2 points.

@yourcelf Found when he downloads his own note, he is prompted to accept -2 karma points for the note, but ends up with +2 karma points because a user downloaded his note.

At very least, both the +2 and -2 should happen so that downloading his own note is a net zero change. If the -2 doesn't happen for one's own notes (as appears to be the case), then we should make sure the relevant check exists to skip the +2 for one's own notes as well.

**Comment by AndrewMagliozzi** [comment]
good catch.  downloading your own note should be a net zero event
