### ISSUE TITLE
Look into replacing FilePicker with Google Picker

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#430]
We have external dependencies on FilePicker for uploading files and Google for converting files.

Google now has Google Picker:
https://developers.google.com/picker/docs/

If we replace FilePicker with Google Picker:

PROs:

* we reduce external dependencies by one
* one less account: most people likely have a Google account already

CONs:

* unlikely to integrate with S3, but free FilePicker accounts can't do that anyway
* overhaul the FilePicker code, upload workflow, and database schema :(

**Comment by AndrewMagliozzi** [comment]
Hey Bryan,

I'm okay paying for file picker. It's $50/mo and pretty handy.

**Comment by btbonval** [comment]
It's more about open source development and that random internet developers
might not be willing to pay.

They don't have to, of course, but it is one more dependency hurdle any new
dev would have to deal with.

**Comment by btbonval** [comment]
Ah @AndrewMagliozzi  reminded me about the missing CON from the above list:

* FilePicker supports way more than just uploading files from the system

That tends to be my only use case, so I forgot FilePicker does a lot more. I think that along with the risk and time to replace FilePicker means the answer to this question is no: we will not replace FilePicker with Google Picker.
