### ISSUE TITLE
karmanotes v karmaworld

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#433]
The repo is called "karmaworld".

However, while updating the documentation, I noticed that "KarmaNotes" continues to be referred to.

I think this might confusing for newcomers.

I will add a naming section that clarifies that KarmaWorld is the software, KarmaNotes is the instance of KarmaWorld as run by FinalsClub. I'll update the documentation to refer to KarmaNotes and KarmaWorld appropriately depending upon whether it discusses production environments or the general software suite.

**Comment by AndrewMagliozzi** [comment]
I'm cool to change the repo name too.

**Comment by btbonval** [comment]
This change is already made and I like the ability to disambiguate
KarmaNotes (the web site) from KarmaWorld (the software).

Like, when discussing Heroku, we're really talking about KarmaNotes in
production, but a user could copy that configuration for their instance of
KarmaWorld. <--- this sentence would be awkward and difficult with a single
name for the software suite and for the production instance run by Finals
Club.

**Comment by btbonval** [comment]
Though if you would rather change the repo name, I can update the docs
again. I don't mean to sound forceful in my response.
