### ISSUE TITLE
Import MIT Notes

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/karmaworld#68]
KarmaNotes is using CC-by on all pages.

inherit OCW CC-by-nc onto OCW pages for both course and note.

possibly create a license table. There'd be two entries to start: index 0 = CC-by, 1 = CC-by-nc. Add license FK into course and note models to license.

Default = 0 for KarmaNotes.

Importing from OCW will explicitly set license to 1.

**Comment by btbonval** [comment]
python script for counting notes per course in the OCW json file.
``` python
import sys
import json
from itertools import imap

# filename supplied as the first argument
filename = sys.argv[1]

# load the json structure from the supplied filename
fd = open(filename, 'r')
fc = json.load(fd)
fd.close()

# prepare some structures
courses = fc['courses']
ncourses = len(courses)
def num_links(obj):
    # return number of links, or 0 if the key is missing
    return (obj.has_key('noteLinks') or 0) and len(obj['noteLinks'])

# sum the notes for all courses
nnotes = sum(imap(num_links, iter(courses)))

print "{0},{1}".format(nnotes, filename)
```
