### ISSUE TITLE
Add courses.cs50.net Harvard course data to production db

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/karmaworld#69]
Scrape courses.cs50.net for Harvard course data if Andrew cannot deliver JSON or XML or an SQL dump prior to launch. 

Add subject to the model.Course

**Comment by btbonval** [comment]
@AndrewMagliozzi Is cs50 data still available somewhere? Curious if we need this ticket open after 2 years later, the data is surely lost in time. I also think we'd be better off focusing on scraping OCW / MOOC systems rather than singular courses for efficiency.

**Comment by btbonval** [comment]
After visiting the site, I now see CS50 is not a singular Computer Science course but appears to be some kind of OCW/MOOC. I'm going to icebox this ticket.

**Comment by AndrewMagliozzi** [comment]
this ticket can be closed

**Comment by btbonval** [comment]
Ticket closed.
